### ISSUE TITLE
enhancement: enable moveTo(x,y)  command 

### ISSUE THREAD

**Issue by robotiko** [mirobot/mirobot-arduino#17]
It would be nice that the moveTo command used in PointAndClick app is moved from web to Arduino code so it can be directly called and reused in other arduino programs.

**Comment by bjpirt** [comment]
It's difficult to add this kind of thing in to the Arduino because it has no concept of this kind of coordinate space, only movements relative to its current position. The point and click app works because it is keeping track of its position and orientation.

**Comment by robotiko** [comment]
ok @bjpirt.
Thanks for considering.
