### ISSUE TITLE
Compile Firmware in Arduino IDE

### ISSUE THREAD

**Issue by mirobotuser** [mirobot/mirobot-arduino#19]
Hello,
I try to compile the Arduino Firmware on my own under the most recent Arduino 1.6.12.
Is there somewhere a script or description, which directories need to go where, so the linker is able to find all libraries?

Thanks for any hint.

  Kuno

**Comment by bjpirt** [comment]
Hi Kuno,
You should just be able to install it through the library manager and then run one of the sample projects. More details here:

http://learn.mirobot.io/docs/update-arduino-serial/

Cheers,
Ben
